sudo: required
language: node_js
node_js:
  - "9"
services:
  - docker

before_install:
  # install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  # login to docker registries (dockerhub + heroku)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com

script:
  # build docker images
  - ./build.sh
  - docker tag unqpdes/todo-list-proxy:latest registry.heroku.com/$HEROKU_APP/web

deploy:
  provider: script
  script:
    # push to dockerhub & heroku
    docker push unqpdes/todo-list-proxy;
    docker push registry.heroku.com/$HEROKU_APP/web;
    heroku container:release web --app $HEROKU_APP
  on:
    branch: master